name: Terraform CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Format & Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.8"

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: infra

      - name: Terraform Init
        run: terraform init -backend=false
        working-directory: infra

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra

  lint:
    name: TFLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Init TFLint
        run: tflint --init
        working-directory: infra

      - name: Run TFLint
        run: tflint --format compact
        working-directory: infra

  security:
    name: Security Scan (Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: infra
          exit-code: "1"
          severity: CRITICAL,HIGH
